Do not report unresolved symbols as errors in the web demo
hkust-taco/mlscript pull request #141
Opened 2022-09-28 09:09 UTC by chengluyu

2022-09-28 09:12 UTC, chengluyu commented on shared/src/main/scala/mlscript/codegen/Polyfill.scala
> +              ) :: Nil)
`JSON.stringify` reports errors for recursive objects. This is the plan B.

2022-09-29 08:44 UTC, LPTK requested changes
Thanks! I merged with the main branch. Please recompile the JS and push it to the PR.

2022-09-29 08:58 UTC, chengluyu commented
Updated. Looks good.

2022-09-29 09:04 UTC, LPTK approved these changes
LGTM

2022-09-29 09:05 UTC, merged