Defunctionalization with simple-sub Control-flow Analysis
hkust-taco/mlscript pull request #222
Opened 2024-05-17 18:56 UTC by HarrisL2

This PR adds an implementation of defunctionalization for selection on objects that uses simple-sub for control flow analysis.

2024-05-20 07:25 UTC, LPTK reviewed
Please remove the old defunctionalizer and port all its tests to this new implementation, and mark the PR as ready.

2024-05-20 07:25 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +  def freshVar(n: String)(using TermId): ((ProdVar), (ConsVar)) =
Weird parens

2024-05-20 07:25 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +  // TODO: remove redundancy between selToObjTypes and selTermToType
Outdated TODO?

2024-05-28 10:02 UTC, LPTK requested changes
Thanks for the PR!

Please move all the test files from `Simpledef` back to `Defunctionalize`, so we get a more useful diff.

It seems you haven't carefully reviewed your tests. They contain lots of "Uncaught error" instances that don't seem justified.

File [Simpledef.scala](https://github.com/hkust-taco/mlscript/pull/222/files#diff-c49577a771fbd4dc62721ad3c6836011c6e58928dc1ee3a5cb90e09e2b3be639) is completely missing any sort of documentation. At the very least give some vey high-level introduction at the beginning and explain what the information stored in each mutable map is.

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/test/diff/Simpledef/ClosureCapture.mls
> +// FIXME: Class parameters not annotated
Why the FIXME?

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/test/diff/Simpledef/Classes.mls
> +:nolift
What are these options and why are they used everywhere? It would seem they should be the default. Otherwise all these lines are just noise.

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/debug/MonomorphError.scala
> +class MonomorphError(error: String) extends Error
Why would this one-line class deserve its own file?

2024-05-28 10:02 UTC, LPTK commented on shared/src/test/scala/mlscript/DiffTests.scala
> -  def nolift: Bool
Why change the order?

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +}
```suggestion
}

```

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/test/diff/Simpledef/RecursiveFunc.mls
> +// FIXME: Strange syntax
What does this mean? And why does it crash?

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/test/diff/Simpledef/ClassConsturctor.mls
> +// TODO: Support NuNew
Why isn't it supported?

2024-05-28 10:02 UTC, LPTK commented on compiler/shared/test/diff/Simpledef/DelayedEvaluation.mls
> +// FIXME: Preserve local state in classes
Is this FIXME still current?

2024-06-04 18:55 UTC, HarrisL2 commented on compiler/shared/test/diff/Defunctionalize/RecursiveFunc.mls
> +// TODO: Support for specialized pattern matching types
Constraining this would require implementing intersections and negative types, which I'm not sure if is within this scope of this PR for now.

2024-06-07 00:30 UTC, LPTK requested changes
Not a fan of what you did to the class lifter tests – sweeping under the rug the fact they are ill-formed (produce runtime crashes) and that the lifter doesn't propagate type annotations when it should. Nevertheless, let's just get this merged ASAP after you address my last comments below.

2024-06-07 00:30 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +{
Trailing commas are better style:
```suggestion
  classes: Map[Var, ProdObj],
) {
```

2024-06-07 00:30 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/ClassLifter.scala
> +class MonomorphError(error: String) extends Error(error)
Why does the class lifter raise a `MonomorphError`? At least rename it to something more generic, such as `CompilerError`.

2024-06-07 00:30 UTC, LPTK commented on shared/src/test/scala/mlscript/DiffTests.scala
> +      postProcessAfterTyping: Bool = false,
I really don't like this. When we discussed this, we agreed to add a _new_ overridable hook after typing, not to make the semantics of the existing one depend on some obscure flag...

2024-06-07 00:30 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +
```suggestion
```

2024-06-07 00:30 UTC, LPTK commented on compiler/shared/main/scala/mlscript/compiler/simpledef/Simpledef.scala
> +  //TODO
TODO what?

2024-06-08 01:06 UTC, LPTK commented
I actually can't tell why you need `:ppat`? Can you please explain it here and also document it?

2024-06-09 15:06 UTC, HarrisL2 commented
After examining the code more, I've deemed the flag unnecessary. I've moved all defunctionalization to the (now separate) post-typing process.

2024-06-17 05:05 UTC, LPTK approved these changes
After this last thing, I think we can finally merge this!

2024-06-17 05:05 UTC, LPTK commented on shared/src/test/scala/mlscript/DiffTests.scala
> +            else if (mode.lift || basePath.contains("Lifter")) {
Please let's remove this hack. I know a similar hack is used elsewhere, but it's not good practice and there's no reason of perpetuating the (mal)practice. Just use the required flags in the required files.

2024-06-18 05:27 UTC, merged