Support for annotations
hkust-taco/mlscript pull request #247
Opened 2024-12-04 08:01 UTC by chengluyu

I'm trying to support annotations. As we discussed, recursive pattern normalization/compilation should be an opt-in feature and can be enabled by an annotation. For example,

```
fun foo(xs) = if xs is
  @compile EmailList(values) then ...
  ...
```

I have only completed parsing as the first step. I am still not sure how it should be handled in the `Elaborator`, so I put this PR in draft status.

2024-12-04 12:48 UTC, LPTK commented
For reference, the PR where this was implemented in the previous version of the compiler by @CAG2Mark: https://github.com/hkust-taco/mlscript/pull/210

2024-12-04 12:50 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +            blk ::: blockContOf(rule) // TODO: apply headAnnotations
Not a fan of this. We're going to be silently dropping some information, which is always the worst to debug, if/when we eventually look into why this case is not working.

Do you have a test case that reproduces this path?

2025-01-08 09:20 UTC, chengluyu commented
### Summary

- Add case `Annotated(qualifier, target)` to both `Tree` and `Terms`.
- Only annotations for declarations are stored in a new field `annotations` added to `LetDecl`, `TermDefinition`, and `TypeLikeDef`. 
- Annotating expressions and missing annotation targets will raise a warning. In such cases, annotation qualifiers will be discarded and not elaborated.
- Annotation qualifiers must be a simple expression of selections or identifiers (or applications to them).

2025-01-08 09:20 UTC, chengluyu commented
Please squash and merge after review. Thanks.

2025-01-08 09:20 UTC, chengluyu commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +            blk ::: blockContOf(rule) // TODO: apply headAnnotations
Thanks. This is fixed.

2025-01-08 10:25 UTC, LPTK requested changes
Thanks, it looks mostly good, but:
* You should probably warn about useless annotations in Lowering rather than Elaborator – indeed, the lowering will later make use of some annotations, like `@tailrec`.
* Similarly, in Lowering, you should warn against useless annotations even on definitions (like class and value definitions).

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/semantics/Elaborator.scala
> +        msg"Because annotations are not supported for ${rhs.describe}" -> rhs.toLoc :: Nil))
```suggestion
        msg"This annotation has no effect." -> lhs.toLoc ::
        msg"Annotations are not supported on ${rhs.describe} terms." -> rhs.toLoc :: Nil))
```

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/semantics/Elaborator.scala
> +    def go(sts: Ls[Tree], qualifiers: Ls[Term], acc: Ls[Statement]): Ctxl[(Term.Blk, Ctx)] =
Why rename to annotations to qualifiers? The former is much clearer and more specific.correct. There are many forms of qualifiers, but annotations are not usually understood as qualifiers.

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Declarations.mls
> +// :pt
Remove the comments? (Below as well.)

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/codegen/Lowering.scala
> +
Weird spaces.

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/codegen/Lowering.scala
> +      // TODO: handle annotations
It seems that the warning about useless annotations should be reported here rather than in the elaborator.

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +            blk.map(qualifiers.annotate) ::: blockContOf(rule) // TODO: apply qualifiers
What is the TODO for?

2025-01-08 10:25 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +                err((msg"Blocks cannot be annotated" -> S(loc) :: Nil))
This error should be diff-tested.

2025-01-09 04:39 UTC, chengluyu commented
It seems that there are still some warnings about unused annotations that need to be addressed in the elaborator, because by the time they reach the lowering phase, these trees are no longer present, such as `open`. Therefore, I kept the warnings in the elaborator when processing blocks.

2025-01-09 04:57 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/semantics/Elaborator.scala
> +            case S(head) => msg"Annotations are not supported on ${head.describe}" -> head.toLoc
```suggestion
            case S(head) => msg"Annotations are not supported on ${head.describe} terms." -> head.toLoc
```

2025-01-09 04:57 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/codegen/Lowering.scala
> +            case cls: ClassLikeDef => cls.kind.desc }." -> target.toLoc :: Nil))
```suggestion
      Nil))
```

2025-01-09 06:58 UTC, chengluyu commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +                err((msg"Blocks cannot be annotated" -> S(loc) :: Nil))
I added a test, but this case is tricky because the condition under which it appears is: the foremost token is an identifier; this identifier is also keyword; this keyword has a rule starting with it in the `prefixRules1, but there is no rule starting with this keyword in the current `rule`.

2025-01-09 06:58 UTC, chengluyu commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +                err((msg"Blocks cannot be annotated" -> S(loc) :: Nil))
I tried adding `???` to understand where it's used by seeing where it crashes, but I found that all of these tests are marked as todo or fixme.

2025-01-09 07:55 UTC, LPTK commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +                err((msg"Blocks cannot be annotated" -> S(loc) :: Nil))
Why are you not simply passing the annotations to the `p.blockOf` call below instead of `Nil`? The error as it is now makes little sense.

2025-01-09 07:56 UTC, LPTK approved these changes
LGTM, thanks.

I'll merge after you the last conversation is resolved.

2025-01-09 08:02 UTC, chengluyu commented on hkmc2/shared/src/main/scala/hkmc2/syntax/Parser.scala
> +                err((msg"Blocks cannot be annotated" -> S(loc) :: Nil))
That's a great idea! I overlooked the fact that it called `blockOf`.

2025-01-09 08:07 UTC, LPTK commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Why remove the test case?

2025-01-09 08:10 UTC, chengluyu commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
The code that produced the error "Blocks cannot be annotated" has been removed, and this code actually couldn't work; it was rewritten from a test block of `ADTs.mls`. It's no longer useful.

2025-01-09 10:13 UTC, LPTK commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Why couldn't this code work? The code looks fine to me.

Clearly, this code was triggering a path in the compiler that was previously untested. So it's important that we keep the test around! Why would you remove it and revert to having that path untested?

2025-01-09 10:26 UTC, chengluyu commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
The code path is tested. There are around 11 test blocks which reveals this code path IIRC, for example, in `ADTs.mls`. Also, the `UnimplementedError` is not caused by any code introduced in this commit and can be found in all other test blocks revealing this code path.

2025-01-09 10:30 UTC, chengluyu commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Here is a test block that reveals the same code path: https://github.com/hkust-taco/mlscript/blob/e9e1354cd539ca8c0d40cdc201b18d6068444d95/hkmc2/shared/src/test/mlscript/basics/ADTs.mls#L14-L18

2025-01-09 10:32 UTC, LPTK commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
I meant that there is no test that tries to annotate a split statement like this. In fact, the test I'd like to see is:
```fs
@debug
val
  x = 1
  y = 2
```

2025-01-09 10:36 UTC, chengluyu commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Do you mean a test like this: https://github.com/hkust-taco/mlscript/blob/e907ad68197d93d63b00bb53fadac7dbed0c0522/hkmc2/shared/src/test/mlscript/syntax/annotations/Declarations.mls#L117-L122

2025-01-09 10:37 UTC, chengluyu commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Or do you want me to specifically introduce a test for `val`?

2025-01-09 12:31 UTC, LPTK commented on hkmc2/shared/src/test/mlscript/syntax/annotations/Unsupported.mls
> -//│ /!!!\ Uncaught error: scala.NotImplementedError: List() (of class Nil$)
Ok that one seems to be enough 👍

2025-01-09 12:32 UTC, merged